export const COUNTRIES: string[] = [
  'Suisse',
  'France',
  'Belgique',
  'Luxembourg',
  'Allemagne',
  'Espagne',
  'Italie',
  'Portugal',
  'Pays-Bas',
  'Royaume-Uni',
  'Autriche',
  'Andorre',
  'Albanie',
  'Arménie',
  'Azerbaïdjan',
  'Biélorussie',
  'Bosnie-Herzégovine',
  'Bulgarie',
  'Chypre',
  'Croatie',
  'Danemark',
  'Estonie',
  'Finlande',
  'Grèce',
  'Hongrie',
  'Irlande',
  'Islande',
  'Kazakhstan',
  'Lettonie',
  'Liechtenstein',
  'Lituanie',
  'Malte',
  'Moldavie',
  'Monaco',
  'Monténégro',
  'Macédoine du Nord',
  'Norvège',
  'Pologne',
  'Roumanie',
  'Saint-Marin',
  'Serbie',
  'Slovaquie',
  'Slovénie',
  'Suède',
  'Tchéquie',
  'Turquie',
  'Ukraine',
  'Vatican',
  'Bénin',
  'Burkina Faso',
  'Burundi',
  'Cameroun',
  'Cap-Vert',
  'Comores',
  'Congo',
  'République démocratique du Congo',
  "Côte d'Ivoire",
  'Djibouti',
  'Égypte',
  'Gabon',
  'Gambie',
  'Ghana',
  'Guinée',
  'Guinée-Bissau',
  'Guinée équatoriale',
  'Kenya',
  'Liberia',
  'Madagascar',
  'Malawi',
  'Mali',
  'Maroc',
  'Maurice',
  'Mauritanie',
  'Mozambique',
  'Namibie',
  'Niger',
  'Nigeria',
  'Ouganda',
  'République centrafricaine',
  'Rwanda',
  'Sao Tomé-et-Principe',
  'Sénégal',
  'Seychelles',
  'Sierra Leone',
  'Somalie',
  'Soudan',
  'Soudan du Sud',
  'Afrique du Sud',
  'Tanzanie',
  'Tchad',
  'Togo',
  'Tunisie',
  'Zambie',
  'Zimbabwe',
  'Afghanistan',
  'Arabie saoudite',
  'Australie',
  'Bahreïn',
  'Bangladesh',
  'Bhoutan',
  'Birmanie (Myanmar)',
  'Brunei',
  'Cambodge',
  'Chine',
  'Corée du Nord',
  'Corée du Sud',
  'Émirats arabes unis',
  'États-Unis',
  'Fidji',
  'Inde',
  'Indonésie',
  'Irak',
  'Iran',
  'Israël',
  'Japon',
  'Jordanie',
  'Koweït',
  'Laos',
  'Liban',
  'Malaisie',
  'Maldives',
  'Mongolie',
  'Népal',
  'Nouvelle-Zélande',
  'Oman',
  'Ouzbékistan',
  'Pakistan',
  'Palestine',
  'Papouasie-Nouvelle-Guinée',
  'Philippines',
  'Qatar',
  'Singapour',
  'Sri Lanka',
  'Syrie',
  'Tadjikistan',
  'Taïwan',
  'Thaïlande',
  'Timor oriental',
  'Turkménistan',
  'Vietnam',
  'Yémen',
  'Argentine',
  'Bolivie',
  'Brésil',
  'Canada',
  'Chili',
  'Colombie',
  'Costa Rica',
  'Cuba',
  'Équateur',
  'El Salvador',
  'Guatemala',
  'Guyana',
  'Haïti',
  'Honduras',
  'Jamaïque',
  'Mexique',
  'Nicaragua',
  'Panama',
  'Paraguay',
  'Pérou',
  'République dominicaine',
  'Trinité-et-Tobago',
  'Uruguay',
  'Venezuela',
].sort((a, b) => a.localeCompare(b, 'fr'))

const ISO_BY_FRENCH_NAME: Record<string, string> = {
  Suisse: 'CH',
  France: 'FR',
  Belgique: 'BE',
  Luxembourg: 'LU',
  Allemagne: 'DE',
  Espagne: 'ES',
  Italie: 'IT',
  Portugal: 'PT',
  'Pays-Bas': 'NL',
  'Royaume-Uni': 'GB',
  Autriche: 'AT',
  Andorre: 'AD',
  Albanie: 'AL',
  Arménie: 'AM',
  Azerbaïdjan: 'AZ',
  Biélorussie: 'BY',
  'Bosnie-Herzégovine': 'BA',
  Bulgarie: 'BG',
  Chypre: 'CY',
  Croatie: 'HR',
  Danemark: 'DK',
  Estonie: 'EE',
  Finlande: 'FI',
  Grèce: 'GR',
  Hongrie: 'HU',
  Irlande: 'IE',
  Islande: 'IS',
  Kazakhstan: 'KZ',
  Lettonie: 'LV',
  Liechtenstein: 'LI',
  Lituanie: 'LT',
  Malte: 'MT',
  Moldavie: 'MD',
  Monaco: 'MC',
  Monténégro: 'ME',
  'Macédoine du Nord': 'MK',
  Norvège: 'NO',
  Pologne: 'PL',
  Roumanie: 'RO',
  'Saint-Marin': 'SM',
  Serbie: 'RS',
  Slovaquie: 'SK',
  Slovénie: 'SI',
  Suède: 'SE',
  Tchéquie: 'CZ',
  Turquie: 'TR',
  Ukraine: 'UA',
  Vatican: 'VA',
  Bénin: 'BJ',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  Cameroun: 'CM',
  'Cap-Vert': 'CV',
  Comores: 'KM',
  Congo: 'CG',
  'République démocratique du Congo': 'CD',
  "Côte d'Ivoire": 'CI',
  Djibouti: 'DJ',
  Égypte: 'EG',
  Gabon: 'GA',
  Gambie: 'GM',
  Ghana: 'GH',
  Guinée: 'GN',
  'Guinée-Bissau': 'GW',
  'Guinée équatoriale': 'GQ',
  Kenya: 'KE',
  Liberia: 'LR',
  Madagascar: 'MG',
  Malawi: 'MW',
  Mali: 'ML',
  Maroc: 'MA',
  Maurice: 'MU',
  Mauritanie: 'MR',
  Mozambique: 'MZ',
  Namibie: 'NA',
  Niger: 'NE',
  Nigeria: 'NG',
  Ouganda: 'UG',
  'République centrafricaine': 'CF',
  Rwanda: 'RW',
  'Sao Tomé-et-Principe': 'ST',
  Sénégal: 'SN',
  Seychelles: 'SC',
  'Sierra Leone': 'SL',
  Somalie: 'SO',
  Soudan: 'SD',
  'Soudan du Sud': 'SS',
  'Afrique du Sud': 'ZA',
  Tanzanie: 'TZ',
  Tchad: 'TD',
  Togo: 'TG',
  Tunisie: 'TN',
  Zambie: 'ZM',
  Zimbabwe: 'ZW',
  Afghanistan: 'AF',
  'Arabie saoudite': 'SA',
  Australie: 'AU',
  Bahreïn: 'BH',
  Bangladesh: 'BD',
  Bhoutan: 'BT',
  'Birmanie (Myanmar)': 'MM',
  Brunei: 'BN',
  Cambodge: 'KH',
  Chine: 'CN',
  'Corée du Nord': 'KP',
  'Corée du Sud': 'KR',
  'Émirats arabes unis': 'AE',
  'États-Unis': 'US',
  Fidji: 'FJ',
  Inde: 'IN',
  Indonésie: 'ID',
  Irak: 'IQ',
  Iran: 'IR',
  Israël: 'IL',
  Japon: 'JP',
  Jordanie: 'JO',
  Koweït: 'KW',
  Laos: 'LA',
  Liban: 'LB',
  Malaisie: 'MY',
  Maldives: 'MV',
  Mongolie: 'MN',
  Népal: 'NP',
  'Nouvelle-Zélande': 'NZ',
  Oman: 'OM',
  Ouzbékistan: 'UZ',
  Pakistan: 'PK',
  Palestine: 'PS',
  'Papouasie-Nouvelle-Guinée': 'PG',
  Philippines: 'PH',
  Qatar: 'QA',
  Singapour: 'SG',
  'Sri Lanka': 'LK',
  Syrie: 'SY',
  Tadjikistan: 'TJ',
  Taïwan: 'TW',
  Thaïlande: 'TH',
  'Timor oriental': 'TL',
  Turkménistan: 'TM',
  Vietnam: 'VN',
  Yémen: 'YE',
  Argentine: 'AR',
  Bolivie: 'BO',
  Brésil: 'BR',
  Canada: 'CA',
  Chili: 'CL',
  Colombie: 'CO',
  'Costa Rica': 'CR',
  Cuba: 'CU',
  Équateur: 'EC',
  'El Salvador': 'SV',
  Guatemala: 'GT',
  Guyana: 'GY',
  Haïti: 'HT',
  Honduras: 'HN',
  Jamaïque: 'JM',
  Mexique: 'MX',
  Nicaragua: 'NI',
  Panama: 'PA',
  Paraguay: 'PY',
  Pérou: 'PE',
  'République dominicaine': 'DO',
  'Trinité-et-Tobago': 'TT',
  Uruguay: 'UY',
  Venezuela: 'VE',
}

export function countryLabel(name: string, locale: string): string {
  const code = ISO_BY_FRENCH_NAME[name]
  if (!code) return name
  try {
    return new Intl.DisplayNames([locale], { type: 'region' }).of(code) ?? name
  } catch {
    return name
  }
}
