export const COUNTRIES: string[] = [
  'Suisse',
  'France',
  'Belgique',
  'Luxembourg',
  'Allemagne',
  'Espagne',
  'Italie',
  'Portugal',
  'Pays-Bas',
  'Royaume-Uni',
  'Autriche',
  'Andorre',
  'Albanie',
  'Arménie',
  'Azerbaïdjan',
  'Biélorussie',
  'Bosnie-Herzégovine',
  'Bulgarie',
  'Chypre',
  'Croatie',
  'Danemark',
  'Estonie',
  'Finlande',
  'Grèce',
  'Hongrie',
  'Irlande',
  'Islande',
  'Kazakhstan',
  'Lettonie',
  'Liechtenstein',
  'Lituanie',
  'Malte',
  'Moldavie',
  'Monaco',
  'Monténégro',
  'Macédoine du Nord',
  'Norvège',
  'Pologne',
  'Roumanie',
  'Saint-Marin',
  'Serbie',
  'Slovaquie',
  'Slovénie',
  'Suède',
  'Tchéquie',
  'Turquie',
  'Ukraine',
  'Vatican',
  'Bénin',
  'Burkina Faso',
  'Burundi',
  'Cameroun',
  'Cap-Vert',
  'Comores',
  'Congo',
  'République démocratique du Congo',
  "Côte d'Ivoire",
  'Djibouti',
  'Égypte',
  'Gabon',
  'Gambie',
  'Ghana',
  'Guinée',
  'Guinée-Bissau',
  'Guinée équatoriale',
  'Kenya',
  'Liberia',
  'Madagascar',
  'Malawi',
  'Mali',
  'Maroc',
  'Maurice',
  'Mauritanie',
  'Mozambique',
  'Namibie',
  'Niger',
  'Nigeria',
  'Ouganda',
  'République centrafricaine',
  'Rwanda',
  'Sao Tomé-et-Principe',
  'Sénégal',
  'Seychelles',
  'Sierra Leone',
  'Somalie',
  'Soudan',
  'Soudan du Sud',
  'Afrique du Sud',
  'Tanzanie',
  'Tchad',
  'Togo',
  'Tunisie',
  'Zambie',
  'Zimbabwe',
  'Afghanistan',
  'Arabie saoudite',
  'Australie',
  'Bahreïn',
  'Bangladesh',
  'Bhoutan',
  'Birmanie (Myanmar)',
  'Brunei',
  'Cambodge',
  'Chine',
  'Corée du Nord',
  'Corée du Sud',
  'Émirats arabes unis',
  'États-Unis',
  'Fidji',
  'Inde',
  'Indonésie',
  'Irak',
  'Iran',
  'Israël',
  'Japon',
  'Jordanie',
  'Koweït',
  'Laos',
  'Liban',
  'Malaisie',
  'Maldives',
  'Mongolie',
  'Népal',
  'Nouvelle-Zélande',
  'Oman',
  'Ouzbékistan',
  'Pakistan',
  'Palestine',
  'Papouasie-Nouvelle-Guinée',
  'Philippines',
  'Qatar',
  'Singapour',
  'Sri Lanka',
  'Syrie',
  'Tadjikistan',
  'Taïwan',
  'Thaïlande',
  'Timor oriental',
  'Turkménistan',
  'Vietnam',
  'Yémen',
  'Argentine',
  'Bolivie',
  'Brésil',
  'Canada',
  'Chili',
  'Colombie',
  'Costa Rica',
  'Cuba',
  'Équateur',
  'El Salvador',
  'Guatemala',
  'Guyana',
  'Haïti',
  'Honduras',
  'Jamaïque',
  'Mexique',
  'Nicaragua',
  'Panama',
  'Paraguay',
  'Pérou',
  'République dominicaine',
  'Trinité-et-Tobago',
  'Uruguay',
  'Venezuela',
].sort((a, b) => a.localeCompare(b, 'fr'))